### ISSUE TITLE
License

### ISSUE THREAD

**Issue by guipotje** [meyiao/xfeatc#2]
Hello,

Thank you for sharing the C++ implementation of XFeat; it looks excellent!

Would it be possible for you to add a license file to the repository?

Best regards,
Guilherme

**Comment by meyiao** [comment]
Hi, 

thank you for your excellent work, you are hero!

I have added the license part in the readme.

Best regards!
meyiao

**Comment by guipotje** [comment]
Thank you so much @meyiao !
