### ISSUE TITLE
RGB Images

### ISSUE THREAD

**Issue by DennisMelamed** [meyiao/xfeatc#3]
Hi! I've re-exported an onnx model to support RGB images, but am running into an issue where the extracted keypoints don't appear to make much sense (they're scattered somewhat randomly throughout the image). Have you tested your code with RGB images? Perhaps there is some subtlety in the process of converting the model outputs to keypoints which needs to change for RGB images? I cannot share the input images I am using, but would expect this result from trying to match any RGB images.

Let me know your thoughts, I'd appreciate any pointers you have to possible problems.

**Comment by meyiao** [comment]
Hi @DennisMelamed 

Thanks for your interest!
I did some tests and found out that you are right, the RGB input can't work properly.
I have modified the code and make the RGB images work, but I don't plan to support RGB input in main branch, so I have pushed the code to the `colorIn` branch: https://github.com/meyiao/xfeatc/tree/colorIn, please check it out.
I have verified the result by comparing the results with the output of the original pytorch model, it looks good. left side is pytorch output, right side is xfeatc output:

![xfeat_pytorch_vs_cpp](https://github.com/user-attachments/assets/9155c6a1-e18d-428e-a3c9-a4cf3a1e5436)
