### ISSUE TITLE
output name cannot be empty

### ISSUE THREAD

**Issue by dapao-0808** [meyiao/xfeatc#5]
Hi! Thank you very much for your work, but I encountered an empty output name while running the code. How did this happen? How should I solve it? The onnx model is based on a 480x640 image that I converted from the example code

![691ae4032358978748aaffa879d1c58f](https://github.com/user-attachments/assets/75862a5f-4d4e-4232-962a-837d59e524bc)

**Comment by meyiao** [comment]
Hi @dapao-0808 , thanks for your interest.
Could you please try to change the OnnxHelper::GetOnnxModelInfo function according to the suggestions given here: https://github.com/microsoft/onnxruntime/issues/20568. 
I will try to solve the issue when I have the time.

**Comment by dapao-0808** [comment]
Thank you very much, this issue has been resolved. I don't know when you have free time to update the onnxrruntime example for xFeat+LighterGlue. I am looking forward to it.

**Comment by meyiao** [comment]
The latest [commit](https://github.com/meyiao/xfeatc/commit/c64e201f2e7bb02227e94b5241205f0dc5bc6fd4) has fixed this issue.

**Comment by meyiao** [comment]
Hi, I'm also interested in XFeat+LighterGlue, but I don't think I have free time to experiment with it in the near future.
