### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by Asherchi** [meyiao/xfeatc#6]
make[2]: *** No rule to make target '/home/xag/Desktop/lib/onnxruntime-linux-x64-1.20.1/lib/onnxruntime.lib', needed by 'FlowDemo'.  Stop.
make[2]: *** Waiting for unfinished jobs....

请问遇到过这个问题吗？

**Comment by Asherchi** [comment]
是因为使用的系统不同，对应的cmakeLists.txt文件修改如下即可：
# onnxruntime
set(ONNXRUNTIME_ROOT xxx/Desktop/lib/onnxruntime-linux-x64-1.18.0)
set(ONNXRUNTIME_INCLUDE_DIRS ${ONNXRUNTIME_ROOT}/include)
set(ONNXRUNTIME_LIBS ${ONNXRUNTIME_ROOT}/lib/libonnxruntime.so)

**Comment by meyiao** [comment]
Hi @Asherchi , 

Thanks a lot. I have fixed the build issue on linux : https://github.com/meyiao/xfeatc/commit/c170d9cedcc46525606f401412528c6048cc3de2
