### ISSUE TITLE
The test results have significant accuracy issues

### ISSUE THREAD

**Issue by zw-92** [meyiao/xfeatc#7]

**Comment by meyiao** [comment]
Any details?

**Comment by zw-92** [comment]
Hello, I'm very sorry to bother you. I changed the input to a color image and used the flexible onnx model for testing, but found that the effect was not very good. After modifying the code for bicubic interpolation to your previous version, I found that the effect has improved during testing. But I encapsulated it into a Python library and tested it on the MegaDepth-1500 dataset, finding that auc20 is at 0.35.

**Comment by Asherchi** [comment]
can you share the bicubic interpolation ? I meet same problems!

**Comment by meyiao** [comment]
hello @zw-92 , 

I have been very careful when implementing the bicubic interpolation part, and compared the c++ results with the original python output, the accuray looked good.

Could you please provide some sample data image pairs, and the matching results?

**Comment by zw-92** [comment]
![1](https://github.com/user-attachments/assets/24da7987-6111-487a-a06b-b0e59167bd08)
![图片](https://github.com/user-attachments/assets/c3ab1bd7-3041-461d-af7b-a4907b6f593d)

**Comment by meyiao** [comment]
Hi @zw-92 , this looks totally wrong. Please refer to https://github.com/meyiao/xfeatc/issues/9

**Comment by zw-92** [comment]
非常感谢您的解答，参考之后，该问题已经解决：
![图片](https://github.com/user-attachments/assets/cf275682-4b6c-4df1-abd5-c115c742cbd1)
