### ISSUE TITLE
原始方法和xfeatc的方法对比

### ISSUE THREAD

**Issue by Asherchi** [meyiao/xfeatc#9]
原始的特征提取和匹配方法相比xfeatc实现的方法有很大的差距
原始的两张数据：
![XAG391_0003](https://github.com/user-attachments/assets/bef8a43b-23a9-4318-88ed-5b01d2e7855b)
![XAG391_0004](https://github.com/user-attachments/assets/e8ed0c5c-78af-4464-bc70-e907fc194ba6)
xfeat的原始方法匹配的效果如下图所示：
![image](https://github.com/user-attachments/assets/90fe6d04-9048-4b1d-895b-fe61b80d8da8)
使用xfeatc的方法的匹配效果如下图所示:
![image](https://github.com/user-attachments/assets/39275bd7-61fe-473e-bffb-70857ea7ae62)
二者之间存在巨大的差距，麻烦问下有何改进的点吗？

**Comment by Asherchi** [comment]
此外， topK的数量都是一样的 都是 4096

**Comment by meyiao** [comment]
@Asherchi 你好，我注意到你的图像数据是800x600的，应该是用的自己转的模型测试的。转模型有一些需要注意的地方：
1. python仓库需要用这个[fork](https://github.com/meyiao/accelerated_features/tree/main)：。因为我把原模型的InstanceNormalization去掉了，转而在预处理步骤对图像做归一化；另外把输出从[B,C,H,W]改成了[B,H,W,C], 这样做后处理时访存更友好，速度更快。
2. 导出模型时，图像长和宽应该是32的整数倍，这个是xfeat本身要求的。比如你的图像是宽800x高600的，那么你的模型大小应该用 800x576, 对应python代码里:    

```python 
# Random input
x = torch.randn(1, 1, 576, 800)
```

我已经转了一个这样大小的模型，请查看最新的 `model/` 文件夹。

**Comment by meyiao** [comment]
用上面的模型测试了一下，输出看着是正常的: 

![test1](https://github.com/user-attachments/assets/3491cdf4-1a3a-48af-a0e1-c6bf98f164d0)

误匹配看着有点多，效果肯定还是 lightglue 会更好，最新的 commit 我加了一个误匹配剔除 (假设你的图片无畸变，如果有畸变的话，点的坐标应该先去畸变再做ransac). 这是剔除后的效果，仍有一些误匹配：

![ransac](https://github.com/user-attachments/assets/5ecf3f63-6feb-40a1-a7d7-4d5b6974aca1)

**Comment by Asherchi** [comment]
好的，非常感谢
